version: "3.3"
services:

  mysql-db:
    image: mysql:5.7
    restart: unless-stopped
    container_name: mysql-dbase
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    container_name: my-admin
    env_file: ./.env
    ports:
      - $PHPMYADMIN_PORT:80
    environment:
      PMA_HOST: mysql-db

  springboot-be:
    depends_on:
      - mysql-db
    image: zaineb12/alpine:151
    container_name: springboot
    env_file: ./.env
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysql-db:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    restart: on-failure

volumes:
  db: