version: "3"
services: 
  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: achatdb
      MYSQL_ROOT_PASSWORD: 
  springboot-app:
    image: springboot-app
#    restart:  always
    build: .
    ports:
      - 8089:8089
    environment:
     MYSQL_HOST: mysqldb
     MYSQL_USER: root
     MYSQL_PASSWORD: 
     MYSQL_PORT: 3306  